import os
import argparse
import pandas as pd
import numpy as np
from supabase import create_client, Client

def get_supabase_client() -> Client:
    # Supabase URL should be the base URL (without /rest/v1/)
    url = os.getenv('SUPABASE_URL')
    if url and url.endswith('/rest/v1/'):
        url = url.rstrip('/rest/v1/')
    key = os.getenv('SUPABASE_SERVICE_ROLE_KEY')
    if not url or not key:
        raise RuntimeError('Supabase credentials not set in environment variables')
    return create_client(url, key)

def upsert_jobs(df: pd.DataFrame, client: Client):
    # Convert DataFrame to list of dicts
    records = df.to_dict(orient='records')
    # Assuming table name is "jobs"
    response = client.table('jobs').upsert(records).execute()
    if getattr(response, 'status_code', 200) >= 400:
        # Try to extract error details
        error_msg = getattr(response, 'content', None) or getattr(response, 'json', lambda: {})()
        raise RuntimeError(f"Supabase upsert failed with status {response.status_code}: {error_msg}")
    print(f"Upserted {len(records)} rows into Supabase 'jobs' table.")

def main():
    parser = argparse.ArgumentParser(description='Upload Kalibrr CSV to Supabase')
    parser.add_argument('--file', required=True, help='Path to the CSV file generated by scraper')
    args = parser.parse_args()
    csv_path = args.file
    if not os.path.isfile(csv_path):
        raise FileNotFoundError(f"CSV file not found: {csv_path}")
    df = pd.read_csv(csv_path, encoding='utf-8')
    # Ganti karakter spasi kosong yang tidak biasa (non-breaking space) dengan spasi biasa
    df = df.replace({'\xa0': ' '}, regex=True)
    # Replace NaN/inf with None for JSON compatibility
    df = df.replace({np.nan: None, np.inf: None, -np.inf: None})
    # Convert column names to lowercase snake_case to match Supabase schema
    df = df.rename(columns=lambda col: col.strip().lower().replace(' ', '_'))
    client = get_supabase_client()
    upsert_jobs(df, client)

if __name__ == '__main__':
    main()
