import os
import glob
import argparse
import pandas as pd
import numpy as np
import dotenv
from supabase import create_client, Client

dotenv.load_dotenv()
def get_supabase_client() -> Client:
    # Supabase URL should be the base URL (without /rest/v1/)
    url = os.getenv('SUPABASE_URL')
    if url and url.endswith('/rest/v1/'):
        url = url.rstrip('/rest/v1/')
    key = os.getenv('SUPABASE_SERVICE_ROLE_KEY')
    if not url or not key:
        raise RuntimeError('Supabase credentials not set in environment variables')
    return create_client(url, key)

def upsert_jobs(df: pd.DataFrame, client: Client):
    # Convert DataFrame to list of dicts
    records = df.to_dict(orient='records')
    # Assuming table name is "jobs"
    response = client.table('jobs').upsert(records).execute()
    if getattr(response, 'status_code', 200) >= 400:
        # Try to extract error details
        error_msg = getattr(response, 'content', None) or getattr(response, 'json', lambda: {})()
        raise RuntimeError(f"Supabase upsert failed with status {response.status_code}: {error_msg}")
    print(f"Upserted {len(records)} rows into Supabase 'jobs' table.")

def main():
    parser = argparse.ArgumentParser(description='Upload Kalibrr CSV to Supabase')
    # 🛠️ PERBAIKAN: required diubah jadi False agar bisa di-Run langsung dari editor
    parser.add_argument('--file', required=False, help='Path to the CSV file generated by scraper')
    args = parser.parse_args()
    
    csv_path = args.file
    
    # 🛠️ LOGIKA OTOMATIS JIKA DI-RUN LANGSUNG DARI EDITOR (Tanpa ngetik --file)
    if not csv_path:
        target_pattern = "result_csv/kalibrr_jobs_*.csv"
        matched_files = glob.glob(target_pattern)
        
        if not matched_files:
            raise FileNotFoundError(
                "Tidak ditemukan file CSV di folder 'result_csv/'. \n"
                "Silakan jalankan scraper.py terlebih dahulu sampai file CSV-nya muncul!"
            )
        
        # Otomatis cari dan ambil file CSV yang paling baru dibuat
        csv_path = max(matched_files, key=os.path.getmtime)
        print(f"[Editor Run] Otomatis mendeteksi file terbaru: {csv_path}")
        
    # Jika memasukkan argumen dengan tanda bintang (wildcard) lewat terminal
    elif '*' in csv_path:
        matched_files = glob.glob(csv_path)
        if not matched_files:
            raise FileNotFoundError(f"Tidak ditemukan file CSV dengan pola: {csv_path}")
        csv_path = max(matched_files, key=os.path.getmtime)
        print(f"[Terminal Run] Menemukan file bertimestamp: {csv_path}")

    # Validasi akhir memastikan file benar-benar ada
    if not os.path.isfile(csv_path):
        raise FileNotFoundError(f"CSV file tidak ditemukan di jalur: {csv_path}")
        
    df = pd.read_csv(csv_path, encoding='utf-8')
    df = df.replace({'\xa0': ' '}, regex=True)
    df = df.replace({np.nan: None, np.inf: None, -np.inf: None})
    df = df.rename(columns=lambda col: col.strip().lower().replace(' ', '_'))
    
    client = get_supabase_client()
    upsert_jobs(df, client)

if __name__ == '__main__':
    main()